# Generated by Django 4.1.2 on 2022-10-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('publisher', models.CharField(max_length=250)),
                ('translator', models.CharField(blank=True, max_length=250)),
                ('cover', models.ImageField(upload_to='covers/')),
            ],
        ),
    ]
