# Generated by Django 4.1.2 on 2023-02-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='img/default_avatars/avatar2.jpg', upload_to='accounts/avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biography'),
        ),
    ]
