# Generated by Django 4.1.2 on 2023-02-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='accounts/default_avatars/avatar1.jpg', upload_to='accounts/avatars/', verbose_name='Avatar'),
        ),
    ]
