# Generated by Django 4.1.2 on 2023-02-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='accounts/default_avatars/avatar2.jpg', upload_to='accounts/avatars/', verbose_name='Avatar'),
        ),
    ]
